//! ActiveX thunk registration.

use crate::vm::stdcall_args;
use crate::vm::Vm;

use super::handlers::{
    in_place_frame_query_interface, in_place_site_get_window_context,
    in_place_site_query_interface, in_place_ui_query_interface, ole_context_sensitive_help,
    ole_get_border, ole_get_window, ole_simple_ok, ole_translate_accelerator, site_add_ref,
    site_get_container, site_get_moniker, site_on_show_window, site_query_interface, site_release,
    site_request_new_object_layout, site_save_object, site_show_object,
};

pub(super) fn register_site_thunks(vm: &mut Vm) {
    // IOleClientSite
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.QueryInterface",
        stdcall_args(3),
        site_query_interface,
    );
    vm.register_import_any_stdcall("pe_vm.ioleclientsite.AddRef", stdcall_args(1), site_add_ref);
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.Release",
        stdcall_args(1),
        site_release,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.SaveObject",
        stdcall_args(1),
        site_save_object,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.GetMoniker",
        stdcall_args(4),
        site_get_moniker,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.GetContainer",
        stdcall_args(2),
        site_get_container,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.ShowObject",
        stdcall_args(1),
        site_show_object,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.OnShowWindow",
        stdcall_args(2),
        site_on_show_window,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleclientsite.RequestNewObjectLayout",
        stdcall_args(1),
        site_request_new_object_layout,
    );

    // IOleInPlaceSite
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.QueryInterface",
        stdcall_args(3),
        in_place_site_query_interface,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.AddRef",
        stdcall_args(1),
        site_add_ref,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.Release",
        stdcall_args(1),
        site_release,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.GetWindow",
        stdcall_args(2),
        ole_get_window,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.ContextSensitiveHelp",
        stdcall_args(2),
        ole_context_sensitive_help,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.CanInPlaceActivate",
        stdcall_args(1),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.OnInPlaceActivate",
        stdcall_args(1),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.OnUIActivate",
        stdcall_args(1),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.GetWindowContext",
        stdcall_args(6),
        in_place_site_get_window_context,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.Scroll",
        stdcall_args(3),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.OnUIDeactivate",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.OnInPlaceDeactivate",
        stdcall_args(1),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.DiscardUndoState",
        stdcall_args(1),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.DeactivateAndUndo",
        stdcall_args(1),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplacesite.OnPosRectChange",
        stdcall_args(2),
        ole_simple_ok,
    );

    // IOleInPlaceUIWindow
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.QueryInterface",
        stdcall_args(3),
        in_place_ui_query_interface,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.AddRef",
        stdcall_args(1),
        site_add_ref,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.Release",
        stdcall_args(1),
        site_release,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.GetWindow",
        stdcall_args(2),
        ole_get_window,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.ContextSensitiveHelp",
        stdcall_args(2),
        ole_context_sensitive_help,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.GetBorder",
        stdcall_args(2),
        ole_get_border,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.RequestBorderSpace",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.SetBorderSpace",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceuiwindow.SetActiveObject",
        stdcall_args(3),
        ole_simple_ok,
    );

    // IOleInPlaceFrame
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.QueryInterface",
        stdcall_args(3),
        in_place_frame_query_interface,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.AddRef",
        stdcall_args(1),
        site_add_ref,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.Release",
        stdcall_args(1),
        site_release,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.GetWindow",
        stdcall_args(2),
        ole_get_window,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.ContextSensitiveHelp",
        stdcall_args(2),
        ole_context_sensitive_help,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.GetBorder",
        stdcall_args(2),
        ole_get_border,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.RequestBorderSpace",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.SetBorderSpace",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.SetActiveObject",
        stdcall_args(3),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.InsertMenus",
        stdcall_args(3),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.SetMenu",
        stdcall_args(4),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.RemoveMenus",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.SetStatusText",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.EnableModeless",
        stdcall_args(2),
        ole_simple_ok,
    );
    vm.register_import_any_stdcall(
        "pe_vm.ioleinplaceframe.TranslateAccelerator",
        stdcall_args(3),
        ole_translate_accelerator,
    );
}
