#[derive(Debug, Clone, Default)]
pub struct LoadConfigDirectory32 {
    pub size: Option<u32>,
    pub time_date_stamp: Option<u32>,
    pub major_version: Option<u16>,
    pub minor_version: Option<u16>,
    pub global_flags_clear: Option<u32>,
    pub global_flags_set: Option<u32>,
    pub critical_section_default_timeout: Option<u32>,
    pub decommit_free_block_threshold: Option<u32>,
    pub decommit_total_free_threshold: Option<u32>,
    pub lock_prefix_table: Option<u32>,
    pub maximum_allocation_size: Option<u32>,
    pub virtual_memory_threshold: Option<u32>,
    pub process_affinity_mask: Option<u32>,
    pub process_heap_flags: Option<u32>,
    pub csd_version: Option<u16>,
    pub dependent_load_flags: Option<u16>,
    pub edit_list: Option<u32>,
    pub security_cookie: Option<u32>,
    pub se_handler_table: Option<u32>,
    pub se_handler_count: Option<u32>,
    pub guard_cf_check_function_pointer: Option<u32>,
    pub guard_cf_dispatch_function_pointer: Option<u32>,
    pub guard_cf_function_table: Option<u32>,
    pub guard_cf_function_count: Option<u32>,
    pub guard_flags: Option<u32>,
}
