//! Standard I/O function stubs for MSVCR100.dll.

use crate::vm::windows::check_stub;
use crate::vm::Vm;

const DLL: &str = "MSVCR100.dll";

macro_rules! stub {
    ($name:ident) => {
        fn $name(vm: &mut Vm, _sp: u32) -> u32 {
            check_stub(vm, DLL, stringify!($name));
            0
        }
    };
}

// File I/O
stub!(fopen_impl);
stub!(fopen_s_impl);
stub!(freopen_impl);
stub!(freopen_s_impl);
stub!(fclose_impl);
stub!(fflush_impl);
stub!(fread_impl);
stub!(fread_s_impl);
stub!(fwrite_impl);
stub!(fgetc_impl);
stub!(fgets_impl);
stub!(fputc_impl);
stub!(fputs_impl);
stub!(fgetwc_impl);
stub!(fgetws_impl);
stub!(fputwc_impl);
stub!(fputws_impl);
stub!(ungetc_impl);
stub!(ungetwc_impl);
stub!(fseek_impl);
stub!(fseeki64_impl);
stub!(ftell_impl);
stub!(ftelli64_impl);
stub!(fsetpos_impl);
stub!(fgetpos_impl);
stub!(rewind_impl);
stub!(feof_impl);
stub!(ferror_impl);
stub!(clearerr_impl);
stub!(clearerr_s_impl);
stub!(setbuf_impl);
stub!(setvbuf_impl);
stub!(tmpfile_impl);
stub!(tmpfile_s_impl);
stub!(tmpnam_impl);
stub!(tmpnam_s_impl);
stub!(tempnam_impl);
stub!(wtmpnam_impl);
stub!(wtmpnam_s_impl);
stub!(wtempnam_impl);
stub!(remove_impl);
stub!(rename_impl);
stub!(wremove_impl);
stub!(wrename_impl);
stub!(perror_impl);
stub!(wperror_impl);

// Console I/O
stub!(getc_impl);
stub!(getchar_impl);
stub!(gets_impl);
stub!(gets_s_impl);
stub!(putc_impl);
stub!(putchar_impl);
stub!(puts_impl);
stub!(getwc_impl);
stub!(getwchar_impl);
stub!(putwc_impl);
stub!(putwchar_impl);
stub!(getch_impl);
stub!(getche_impl);
stub!(ungetch_impl);
stub!(getwch_impl);
stub!(getwche_impl);
stub!(ungetwch_impl);
stub!(kbhit_impl);
stub!(cgets_impl);
stub!(cgets_s_impl);
stub!(cgetws_impl);
stub!(cgetws_s_impl);
stub!(cputs_impl);
stub!(cputws_impl);
stub!(getch_nolock_impl);
stub!(getche_nolock_impl);
stub!(ungetch_nolock_impl);
stub!(getwch_nolock_impl);
stub!(getwche_nolock_impl);
stub!(ungetwch_nolock_impl);
stub!(getc_nolock_impl);
stub!(putc_nolock_impl);
stub!(ungetc_nolock_impl);
stub!(getwc_nolock_impl);
stub!(putwc_nolock_impl);
stub!(ungetwc_nolock_impl);

// Printf family
stub!(printf_impl);
stub!(printf_s_impl);
stub!(printf_l_impl);
stub!(printf_s_l_impl);
stub!(printf_p_impl);
stub!(printf_p_l_impl);
stub!(wprintf_impl);
stub!(wprintf_s_impl);
stub!(wprintf_l_impl);
stub!(wprintf_s_l_impl);
stub!(wprintf_p_impl);
stub!(wprintf_p_l_impl);
stub!(fprintf_impl);
stub!(fprintf_s_impl);
stub!(fprintf_l_impl);
stub!(fprintf_s_l_impl);
stub!(fprintf_p_impl);
stub!(fprintf_p_l_impl);
stub!(fwprintf_impl);
stub!(fwprintf_s_impl);
stub!(fwprintf_l_impl);
stub!(fwprintf_s_l_impl);
stub!(fwprintf_p_impl);
stub!(fwprintf_p_l_impl);
stub!(sprintf_impl);
stub!(sprintf_s_impl);
stub!(sprintf_l_impl);
stub!(sprintf_s_l_impl);
stub!(sprintf_p_impl);
stub!(sprintf_p_l_impl);
stub!(swprintf_impl);
stub!(swprintf_s_impl);
stub!(swprintf_c_impl);
stub!(swprintf_c_l_impl);
stub!(swprintf_l_impl);
stub!(swprintf_s_l_impl);
stub!(swprintf_p_impl);
stub!(swprintf_p_l_impl);
stub!(snprintf_impl);
stub!(snprintf_s_impl);
stub!(snprintf_l_impl);
stub!(snprintf_s_l_impl);
stub!(snprintf_c_impl);
stub!(snprintf_c_l_impl);
stub!(snwprintf_impl);
stub!(snwprintf_s_impl);
stub!(snwprintf_l_impl);
stub!(snwprintf_s_l_impl);
stub!(scprintf_impl);
stub!(scprintf_l_impl);
stub!(scprintf_p_impl);
stub!(scprintf_p_l_impl);
stub!(scwprintf_impl);
stub!(scwprintf_l_impl);
stub!(scwprintf_p_impl);
stub!(scwprintf_p_l_impl);
stub!(cprintf_impl);
stub!(cprintf_l_impl);
stub!(cprintf_s_impl);
stub!(cprintf_s_l_impl);
stub!(cprintf_p_impl);
stub!(cprintf_p_l_impl);
stub!(cwprintf_impl);
stub!(cwprintf_l_impl);
stub!(cwprintf_s_impl);
stub!(cwprintf_s_l_impl);
stub!(cwprintf_p_impl);
stub!(cwprintf_p_l_impl);

// Vprintf family
stub!(vprintf_impl);
stub!(vprintf_s_impl);
stub!(vprintf_l_impl);
stub!(vprintf_s_l_impl);
stub!(vprintf_p_impl);
stub!(vprintf_p_l_impl);
stub!(vwprintf_impl);
stub!(vwprintf_s_impl);
stub!(vwprintf_l_impl);
stub!(vwprintf_s_l_impl);
stub!(vwprintf_p_impl);
stub!(vwprintf_p_l_impl);
stub!(vfprintf_impl);
stub!(vfprintf_s_impl);
stub!(vfprintf_l_impl);
stub!(vfprintf_s_l_impl);
stub!(vfprintf_p_impl);
stub!(vfprintf_p_l_impl);
stub!(vfwprintf_impl);
stub!(vfwprintf_s_impl);
stub!(vfwprintf_l_impl);
stub!(vfwprintf_s_l_impl);
stub!(vfwprintf_p_impl);
stub!(vfwprintf_p_l_impl);
stub!(vsprintf_impl);
stub!(vsprintf_s_impl);
stub!(vsprintf_l_impl);
stub!(vsprintf_s_l_impl);
stub!(vsprintf_p_impl);
stub!(vsprintf_p_l_impl);
stub!(vswprintf_impl);
stub!(vswprintf_s_impl);
stub!(vswprintf_c_impl);
stub!(vswprintf_c_l_impl);
stub!(vswprintf_l_impl);
stub!(vswprintf_s_l_impl);
stub!(vswprintf_p_impl);
stub!(vswprintf_p_l_impl);
stub!(vsnprintf_impl);
stub!(vsnprintf_s_impl);
stub!(vsnprintf_l_impl);
stub!(vsnprintf_s_l_impl);
stub!(vsnprintf_c_impl);
stub!(vsnprintf_c_l_impl);
stub!(vsnwprintf_impl);
stub!(vsnwprintf_s_impl);
stub!(vsnwprintf_l_impl);
stub!(vsnwprintf_s_l_impl);
stub!(vscprintf_impl);
stub!(vscprintf_l_impl);
stub!(vscprintf_p_impl);
stub!(vscprintf_p_l_impl);
stub!(vscwprintf_impl);
stub!(vscwprintf_l_impl);
stub!(vscwprintf_p_impl);
stub!(vscwprintf_p_l_impl);
stub!(vcprintf_impl);
stub!(vcprintf_l_impl);
stub!(vcprintf_s_impl);
stub!(vcprintf_s_l_impl);
stub!(vcprintf_p_impl);
stub!(vcprintf_p_l_impl);
stub!(vcwprintf_impl);
stub!(vcwprintf_l_impl);
stub!(vcwprintf_s_impl);
stub!(vcwprintf_s_l_impl);
stub!(vcwprintf_p_impl);
stub!(vcwprintf_p_l_impl);

// Scanf family
stub!(scanf_impl);
stub!(scanf_s_impl);
stub!(scanf_l_impl);
stub!(scanf_s_l_impl);
stub!(wscanf_impl);
stub!(wscanf_s_impl);
stub!(wscanf_l_impl);
stub!(wscanf_s_l_impl);
stub!(fscanf_impl);
stub!(fscanf_s_impl);
stub!(fscanf_l_impl);
stub!(fscanf_s_l_impl);
stub!(fwscanf_impl);
stub!(fwscanf_s_impl);
stub!(fwscanf_l_impl);
stub!(fwscanf_s_l_impl);
stub!(sscanf_impl);
stub!(sscanf_s_impl);
stub!(sscanf_l_impl);
stub!(sscanf_s_l_impl);
stub!(swscanf_impl);
stub!(swscanf_s_impl);
stub!(swscanf_l_impl);
stub!(swscanf_s_l_impl);
stub!(cscanf_impl);
stub!(cscanf_s_impl);
stub!(cscanf_l_impl);
stub!(cscanf_s_l_impl);
stub!(cwscanf_impl);
stub!(cwscanf_s_impl);
stub!(cwscanf_l_impl);
stub!(cwscanf_s_l_impl);

// IOB functions
stub!(iob_func);
stub!(lock_file);
stub!(unlock_file);
stub!(fileno);
stub!(fdopen);
stub!(wfdopen);
stub!(setmode);
stub!(filbuf);
stub!(flsbuf);
stub!(getmaxstdio);
stub!(setmaxstdio);

pub fn register(vm: &mut Vm) {
    // File I/O
    vm.register_import(DLL, "fopen", fopen_impl);
    vm.register_import(DLL, "fopen_s", fopen_s_impl);
    vm.register_import(DLL, "freopen", freopen_impl);
    vm.register_import(DLL, "freopen_s", freopen_s_impl);
    vm.register_import(DLL, "fclose", fclose_impl);
    vm.register_import(DLL, "fflush", fflush_impl);
    vm.register_import(DLL, "fread", fread_impl);
    vm.register_import(DLL, "fread_s", fread_s_impl);
    vm.register_import(DLL, "fwrite", fwrite_impl);
    vm.register_import(DLL, "fgetc", fgetc_impl);
    vm.register_import(DLL, "fgets", fgets_impl);
    vm.register_import(DLL, "fputc", fputc_impl);
    vm.register_import(DLL, "fputs", fputs_impl);
    vm.register_import(DLL, "fgetwc", fgetwc_impl);
    vm.register_import(DLL, "fgetws", fgetws_impl);
    vm.register_import(DLL, "fputwc", fputwc_impl);
    vm.register_import(DLL, "fputws", fputws_impl);
    vm.register_import(DLL, "ungetc", ungetc_impl);
    vm.register_import(DLL, "ungetwc", ungetwc_impl);
    vm.register_import(DLL, "fseek", fseek_impl);
    vm.register_import(DLL, "_fseeki64", fseeki64_impl);
    vm.register_import(DLL, "ftell", ftell_impl);
    vm.register_import(DLL, "_ftelli64", ftelli64_impl);
    vm.register_import(DLL, "fsetpos", fsetpos_impl);
    vm.register_import(DLL, "fgetpos", fgetpos_impl);
    vm.register_import(DLL, "rewind", rewind_impl);
    vm.register_import(DLL, "feof", feof_impl);
    vm.register_import(DLL, "ferror", ferror_impl);
    vm.register_import(DLL, "clearerr", clearerr_impl);
    vm.register_import(DLL, "clearerr_s", clearerr_s_impl);
    vm.register_import(DLL, "setbuf", setbuf_impl);
    vm.register_import(DLL, "setvbuf", setvbuf_impl);
    vm.register_import(DLL, "tmpfile", tmpfile_impl);
    vm.register_import(DLL, "tmpfile_s", tmpfile_s_impl);
    vm.register_import(DLL, "tmpnam", tmpnam_impl);
    vm.register_import(DLL, "tmpnam_s", tmpnam_s_impl);
    vm.register_import(DLL, "_tempnam", tempnam_impl);
    vm.register_import(DLL, "_wtmpnam", wtmpnam_impl);
    vm.register_import(DLL, "_wtmpnam_s", wtmpnam_s_impl);
    vm.register_import(DLL, "_wtempnam", wtempnam_impl);
    vm.register_import(DLL, "remove", remove_impl);
    vm.register_import(DLL, "rename", rename_impl);
    vm.register_import(DLL, "_wremove", wremove_impl);
    vm.register_import(DLL, "_wrename", wrename_impl);
    vm.register_import(DLL, "perror", perror_impl);
    vm.register_import(DLL, "_wperror", wperror_impl);

    // Console I/O
    vm.register_import(DLL, "getc", getc_impl);
    vm.register_import(DLL, "getchar", getchar_impl);
    vm.register_import(DLL, "gets", gets_impl);
    vm.register_import(DLL, "gets_s", gets_s_impl);
    vm.register_import(DLL, "putc", putc_impl);
    vm.register_import(DLL, "putchar", putchar_impl);
    vm.register_import(DLL, "puts", puts_impl);
    vm.register_import(DLL, "getwc", getwc_impl);
    vm.register_import(DLL, "getwchar", getwchar_impl);
    vm.register_import(DLL, "putwc", putwc_impl);
    vm.register_import(DLL, "putwchar", putwchar_impl);
    vm.register_import(DLL, "_getch", getch_impl);
    vm.register_import(DLL, "_getche", getche_impl);
    vm.register_import(DLL, "_ungetch", ungetch_impl);
    vm.register_import(DLL, "_getwch", getwch_impl);
    vm.register_import(DLL, "_getwche", getwche_impl);
    vm.register_import(DLL, "_ungetwch", ungetwch_impl);
    vm.register_import(DLL, "_kbhit", kbhit_impl);
    vm.register_import(DLL, "_cgets", cgets_impl);
    vm.register_import(DLL, "_cgets_s", cgets_s_impl);
    vm.register_import(DLL, "_cgetws", cgetws_impl);
    vm.register_import(DLL, "_cgetws_s", cgetws_s_impl);
    vm.register_import(DLL, "_cputs", cputs_impl);
    vm.register_import(DLL, "_cputws", cputws_impl);
    vm.register_import(DLL, "_getch_nolock", getch_nolock_impl);
    vm.register_import(DLL, "_getche_nolock", getche_nolock_impl);
    vm.register_import(DLL, "_ungetch_nolock", ungetch_nolock_impl);
    vm.register_import(DLL, "_getwch_nolock", getwch_nolock_impl);
    vm.register_import(DLL, "_getwche_nolock", getwche_nolock_impl);
    vm.register_import(DLL, "_ungetwch_nolock", ungetwch_nolock_impl);
    vm.register_import(DLL, "_getc_nolock", getc_nolock_impl);
    vm.register_import(DLL, "_putc_nolock", putc_nolock_impl);
    vm.register_import(DLL, "_ungetc_nolock", ungetc_nolock_impl);
    vm.register_import(DLL, "_getwc_nolock", getwc_nolock_impl);
    vm.register_import(DLL, "_putwc_nolock", putwc_nolock_impl);
    vm.register_import(DLL, "_ungetwc_nolock", ungetwc_nolock_impl);

    // Printf family
    vm.register_import(DLL, "printf", printf_impl);
    vm.register_import(DLL, "printf_s", printf_s_impl);
    vm.register_import(DLL, "_printf_l", printf_l_impl);
    vm.register_import(DLL, "_printf_s_l", printf_s_l_impl);
    vm.register_import(DLL, "_printf_p", printf_p_impl);
    vm.register_import(DLL, "_printf_p_l", printf_p_l_impl);
    vm.register_import(DLL, "wprintf", wprintf_impl);
    vm.register_import(DLL, "wprintf_s", wprintf_s_impl);
    vm.register_import(DLL, "_wprintf_l", wprintf_l_impl);
    vm.register_import(DLL, "_wprintf_s_l", wprintf_s_l_impl);
    vm.register_import(DLL, "_wprintf_p", wprintf_p_impl);
    vm.register_import(DLL, "_wprintf_p_l", wprintf_p_l_impl);
    vm.register_import(DLL, "fprintf", fprintf_impl);
    vm.register_import(DLL, "fprintf_s", fprintf_s_impl);
    vm.register_import(DLL, "_fprintf_l", fprintf_l_impl);
    vm.register_import(DLL, "_fprintf_s_l", fprintf_s_l_impl);
    vm.register_import(DLL, "_fprintf_p", fprintf_p_impl);
    vm.register_import(DLL, "_fprintf_p_l", fprintf_p_l_impl);
    vm.register_import(DLL, "fwprintf", fwprintf_impl);
    vm.register_import(DLL, "fwprintf_s", fwprintf_s_impl);
    vm.register_import(DLL, "_fwprintf_l", fwprintf_l_impl);
    vm.register_import(DLL, "_fwprintf_s_l", fwprintf_s_l_impl);
    vm.register_import(DLL, "_fwprintf_p", fwprintf_p_impl);
    vm.register_import(DLL, "_fwprintf_p_l", fwprintf_p_l_impl);
    vm.register_import(DLL, "sprintf", sprintf_impl);
    vm.register_import(DLL, "sprintf_s", sprintf_s_impl);
    vm.register_import(DLL, "_sprintf_l", sprintf_l_impl);
    vm.register_import(DLL, "_sprintf_s_l", sprintf_s_l_impl);
    vm.register_import(DLL, "_sprintf_p", sprintf_p_impl);
    vm.register_import(DLL, "_sprintf_p_l", sprintf_p_l_impl);
    vm.register_import(DLL, "_swprintf", swprintf_impl);
    vm.register_import(DLL, "swprintf_s", swprintf_s_impl);
    vm.register_import(DLL, "_swprintf_c", swprintf_c_impl);
    vm.register_import(DLL, "_swprintf_c_l", swprintf_c_l_impl);
    vm.register_import(DLL, "_swprintf_l", swprintf_l_impl);
    vm.register_import(DLL, "_swprintf_s_l", swprintf_s_l_impl);
    vm.register_import(DLL, "_swprintf_p", swprintf_p_impl);
    vm.register_import(DLL, "_swprintf_p_l", swprintf_p_l_impl);
    vm.register_import(DLL, "_snprintf", snprintf_impl);
    vm.register_import(DLL, "_snprintf_s", snprintf_s_impl);
    vm.register_import(DLL, "_snprintf_l", snprintf_l_impl);
    vm.register_import(DLL, "_snprintf_s_l", snprintf_s_l_impl);
    vm.register_import(DLL, "_snprintf_c", snprintf_c_impl);
    vm.register_import(DLL, "_snprintf_c_l", snprintf_c_l_impl);
    vm.register_import(DLL, "_snwprintf", snwprintf_impl);
    vm.register_import(DLL, "_snwprintf_s", snwprintf_s_impl);
    vm.register_import(DLL, "_snwprintf_l", snwprintf_l_impl);
    vm.register_import(DLL, "_snwprintf_s_l", snwprintf_s_l_impl);
    vm.register_import(DLL, "_scprintf", scprintf_impl);
    vm.register_import(DLL, "_scprintf_l", scprintf_l_impl);
    vm.register_import(DLL, "_scprintf_p", scprintf_p_impl);
    vm.register_import(DLL, "_scprintf_p_l", scprintf_p_l_impl);
    vm.register_import(DLL, "_scwprintf", scwprintf_impl);
    vm.register_import(DLL, "_scwprintf_l", scwprintf_l_impl);
    vm.register_import(DLL, "_scwprintf_p", scwprintf_p_impl);
    vm.register_import(DLL, "_scwprintf_p_l", scwprintf_p_l_impl);
    vm.register_import(DLL, "_cprintf", cprintf_impl);
    vm.register_import(DLL, "_cprintf_l", cprintf_l_impl);
    vm.register_import(DLL, "_cprintf_s", cprintf_s_impl);
    vm.register_import(DLL, "_cprintf_s_l", cprintf_s_l_impl);
    vm.register_import(DLL, "_cprintf_p", cprintf_p_impl);
    vm.register_import(DLL, "_cprintf_p_l", cprintf_p_l_impl);
    vm.register_import(DLL, "_cwprintf", cwprintf_impl);
    vm.register_import(DLL, "_cwprintf_l", cwprintf_l_impl);
    vm.register_import(DLL, "_cwprintf_s", cwprintf_s_impl);
    vm.register_import(DLL, "_cwprintf_s_l", cwprintf_s_l_impl);
    vm.register_import(DLL, "_cwprintf_p", cwprintf_p_impl);
    vm.register_import(DLL, "_cwprintf_p_l", cwprintf_p_l_impl);

    // Vprintf family
    vm.register_import(DLL, "vprintf", vprintf_impl);
    vm.register_import(DLL, "vprintf_s", vprintf_s_impl);
    vm.register_import(DLL, "_vprintf_l", vprintf_l_impl);
    vm.register_import(DLL, "_vprintf_s_l", vprintf_s_l_impl);
    vm.register_import(DLL, "_vprintf_p", vprintf_p_impl);
    vm.register_import(DLL, "_vprintf_p_l", vprintf_p_l_impl);
    vm.register_import(DLL, "vwprintf", vwprintf_impl);
    vm.register_import(DLL, "vwprintf_s", vwprintf_s_impl);
    vm.register_import(DLL, "_vwprintf_l", vwprintf_l_impl);
    vm.register_import(DLL, "_vwprintf_s_l", vwprintf_s_l_impl);
    vm.register_import(DLL, "_vwprintf_p", vwprintf_p_impl);
    vm.register_import(DLL, "_vwprintf_p_l", vwprintf_p_l_impl);
    vm.register_import(DLL, "vfprintf", vfprintf_impl);
    vm.register_import(DLL, "vfprintf_s", vfprintf_s_impl);
    vm.register_import(DLL, "_vfprintf_l", vfprintf_l_impl);
    vm.register_import(DLL, "_vfprintf_s_l", vfprintf_s_l_impl);
    vm.register_import(DLL, "_vfprintf_p", vfprintf_p_impl);
    vm.register_import(DLL, "_vfprintf_p_l", vfprintf_p_l_impl);
    vm.register_import(DLL, "vfwprintf", vfwprintf_impl);
    vm.register_import(DLL, "vfwprintf_s", vfwprintf_s_impl);
    vm.register_import(DLL, "_vfwprintf_l", vfwprintf_l_impl);
    vm.register_import(DLL, "_vfwprintf_s_l", vfwprintf_s_l_impl);
    vm.register_import(DLL, "_vfwprintf_p", vfwprintf_p_impl);
    vm.register_import(DLL, "_vfwprintf_p_l", vfwprintf_p_l_impl);
    vm.register_import(DLL, "vsprintf", vsprintf_impl);
    vm.register_import(DLL, "vsprintf_s", vsprintf_s_impl);
    vm.register_import(DLL, "_vsprintf_l", vsprintf_l_impl);
    vm.register_import(DLL, "_vsprintf_s_l", vsprintf_s_l_impl);
    vm.register_import(DLL, "_vsprintf_p", vsprintf_p_impl);
    vm.register_import(DLL, "_vsprintf_p_l", vsprintf_p_l_impl);
    vm.register_import(DLL, "_vswprintf", vswprintf_impl);
    vm.register_import(DLL, "vswprintf_s", vswprintf_s_impl);
    vm.register_import(DLL, "_vswprintf_c", vswprintf_c_impl);
    vm.register_import(DLL, "_vswprintf_c_l", vswprintf_c_l_impl);
    vm.register_import(DLL, "_vswprintf_l", vswprintf_l_impl);
    vm.register_import(DLL, "_vswprintf_s_l", vswprintf_s_l_impl);
    vm.register_import(DLL, "_vswprintf_p", vswprintf_p_impl);
    vm.register_import(DLL, "_vswprintf_p_l", vswprintf_p_l_impl);
    vm.register_import(DLL, "__vswprintf_l", vswprintf_l_impl);
    vm.register_import(DLL, "_vsnprintf", vsnprintf_impl);
    vm.register_import(DLL, "_vsnprintf_s", vsnprintf_s_impl);
    vm.register_import(DLL, "_vsnprintf_l", vsnprintf_l_impl);
    vm.register_import(DLL, "_vsnprintf_s_l", vsnprintf_s_l_impl);
    vm.register_import(DLL, "_vsnprintf_c", vsnprintf_c_impl);
    vm.register_import(DLL, "_vsnprintf_c_l", vsnprintf_c_l_impl);
    vm.register_import(DLL, "_vsnwprintf", vsnwprintf_impl);
    vm.register_import(DLL, "_vsnwprintf_s", vsnwprintf_s_impl);
    vm.register_import(DLL, "_vsnwprintf_l", vsnwprintf_l_impl);
    vm.register_import(DLL, "_vsnwprintf_s_l", vsnwprintf_s_l_impl);
    vm.register_import(DLL, "_vscprintf", vscprintf_impl);
    vm.register_import(DLL, "_vscprintf_l", vscprintf_l_impl);
    vm.register_import(DLL, "_vscprintf_p", vscprintf_p_impl);
    vm.register_import(DLL, "_vscprintf_p_l", vscprintf_p_l_impl);
    vm.register_import(DLL, "_vscwprintf", vscwprintf_impl);
    vm.register_import(DLL, "_vscwprintf_l", vscwprintf_l_impl);
    vm.register_import(DLL, "_vscwprintf_p", vscwprintf_p_impl);
    vm.register_import(DLL, "_vscwprintf_p_l", vscwprintf_p_l_impl);
    vm.register_import(DLL, "_vcprintf", vcprintf_impl);
    vm.register_import(DLL, "_vcprintf_l", vcprintf_l_impl);
    vm.register_import(DLL, "_vcprintf_s", vcprintf_s_impl);
    vm.register_import(DLL, "_vcprintf_s_l", vcprintf_s_l_impl);
    vm.register_import(DLL, "_vcprintf_p", vcprintf_p_impl);
    vm.register_import(DLL, "_vcprintf_p_l", vcprintf_p_l_impl);
    vm.register_import(DLL, "_vcwprintf", vcwprintf_impl);
    vm.register_import(DLL, "_vcwprintf_l", vcwprintf_l_impl);
    vm.register_import(DLL, "_vcwprintf_s", vcwprintf_s_impl);
    vm.register_import(DLL, "_vcwprintf_s_l", vcwprintf_s_l_impl);
    vm.register_import(DLL, "_vcwprintf_p", vcwprintf_p_impl);
    vm.register_import(DLL, "_vcwprintf_p_l", vcwprintf_p_l_impl);

    // Scanf family
    vm.register_import(DLL, "scanf", scanf_impl);
    vm.register_import(DLL, "scanf_s", scanf_s_impl);
    vm.register_import(DLL, "_scanf_l", scanf_l_impl);
    vm.register_import(DLL, "_scanf_s_l", scanf_s_l_impl);
    vm.register_import(DLL, "wscanf", wscanf_impl);
    vm.register_import(DLL, "wscanf_s", wscanf_s_impl);
    vm.register_import(DLL, "_wscanf_l", wscanf_l_impl);
    vm.register_import(DLL, "_wscanf_s_l", wscanf_s_l_impl);
    vm.register_import(DLL, "fscanf", fscanf_impl);
    vm.register_import(DLL, "fscanf_s", fscanf_s_impl);
    vm.register_import(DLL, "_fscanf_l", fscanf_l_impl);
    vm.register_import(DLL, "_fscanf_s_l", fscanf_s_l_impl);
    vm.register_import(DLL, "fwscanf", fwscanf_impl);
    vm.register_import(DLL, "fwscanf_s", fwscanf_s_impl);
    vm.register_import(DLL, "_fwscanf_l", fwscanf_l_impl);
    vm.register_import(DLL, "_fwscanf_s_l", fwscanf_s_l_impl);
    vm.register_import(DLL, "sscanf", sscanf_impl);
    vm.register_import(DLL, "sscanf_s", sscanf_s_impl);
    vm.register_import(DLL, "_sscanf_l", sscanf_l_impl);
    vm.register_import(DLL, "_sscanf_s_l", sscanf_s_l_impl);
    vm.register_import(DLL, "swscanf", swscanf_impl);
    vm.register_import(DLL, "swscanf_s", swscanf_s_impl);
    vm.register_import(DLL, "_swscanf_l", swscanf_l_impl);
    vm.register_import(DLL, "_swscanf_s_l", swscanf_s_l_impl);
    vm.register_import(DLL, "_cscanf", cscanf_impl);
    vm.register_import(DLL, "_cscanf_s", cscanf_s_impl);
    vm.register_import(DLL, "_cscanf_l", cscanf_l_impl);
    vm.register_import(DLL, "_cscanf_s_l", cscanf_s_l_impl);
    vm.register_import(DLL, "_cwscanf", cwscanf_impl);
    vm.register_import(DLL, "_cwscanf_s", cwscanf_s_impl);
    vm.register_import(DLL, "_cwscanf_l", cwscanf_l_impl);
    vm.register_import(DLL, "_cwscanf_s_l", cwscanf_s_l_impl);

    // IOB/file functions
    vm.register_import(DLL, "__iob_func", iob_func);
    vm.register_import(DLL, "__p__iob", iob_func);
    vm.register_import(DLL, "_lock_file", lock_file);
    vm.register_import(DLL, "_unlock_file", unlock_file);
    vm.register_import(DLL, "_fileno", fileno);
    vm.register_import(DLL, "_fdopen", fdopen);
    vm.register_import(DLL, "_wfdopen", wfdopen);
    vm.register_import(DLL, "_setmode", setmode);
    vm.register_import(DLL, "_filbuf", filbuf);
    vm.register_import(DLL, "_flsbuf", flsbuf);
    vm.register_import(DLL, "_getmaxstdio", getmaxstdio);
    vm.register_import(DLL, "_setmaxstdio", setmaxstdio);
}
